CREATE TABLE users (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE news (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    author INT,
    title VARCHAR(50) NOT NULL,
    article TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(author) REFERENCES users(id) 
);

CREATE TABLE comments (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    user VARCHAR(30) NOT NULL,
    msg TEXT NOT NULL,
    date DATETIME DEFAULT CURRENT_TIMESTAMP
);
